_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
                - 51
                - 55
            "2":
                - 1
                - 41
                - 51
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.7
            "8":
                - 2
                - 5
            "12": 0.18.7
            "13": linux-x86_64
abs_sort:
    value: true
checkpoint_path:
    value: null
dataset_name:
    value: waterbirds
dataset_path:
    value: /scratch_shared/primmere/waterbird
domain_restriction_classes:
    value: 3
fully_connected_layers_rule:
    value: Epsilon
high_level_hidden_layer_rule:
    value: Epsilon
init_relevance:
    value: 1
least_relevant_first:
    value: true
low_level_hidden_layer_rule:
    value: Epsilon
mid_level_hidden_layer_rule:
    value: Epsilon
mode:
    value: Relevance
model_architecture:
    value: vit_b_16
output_path:
    value: /home/primmere/logs/pxp/results/
pruning_dataloader_batchsize:
    value: 1
pruning_layer_type:
    value: Softmax
pruning_rates:
    value:
        - 0
        - 0.1
        - 0.2
        - 0.3
random_seed:
    value: 0
reference_samples_per_class:
    value: 10
results_file_name:
    value: accuracy_vit_b_16_Relevance_None_sortTrue_leastvalueTrue_0
softmax_rule:
    value: Epsilon
subsequent_layer_pruning:
    value: None
validation_dataloader_batchsize:
    value: 16
wandb:
    value: true
wandb_api_key:
    value: eb7cc596491b2b488bee66037dde6b9c7fb2a837
wandb_project_name:
    value: null
